version: "3"
services:
  redis:
    image: redis:4.0
    ports:
      - 6379:6379
    command: redis-server /usr/local/etc/redis.conf
    volumes:
      - redis-data:/data
      - ./util/docker/redis/redis.conf:/usr/local/etc/redis.conf

volumes:
  redis-data:

